### PR TITLE
Adding Sign up page for user

### PR DESCRIPTION
**Pull request by kamilamin**
Adding Sign up page for Users

### CODE REVIEW

**Comment by redknitin** [comment]
Hello @kamilamin !

This is a good start! 

With the sign-up template created, you would need to define a route to tell the application at what URL it should show the sign-up page. Look at the routes directory and you can see how all the other routes are defined.

BTW, do you have your development environment setup? You would need Git, VirtualBox 5.1, and Vagrant for a simple setup.

**Comment by redknitin** [comment]
Hi @kamilamin !

Did you get a chance to setup your development environment?

**Comment by kamilamin** [comment]
How to get chance to setup your development environment ?


________________________________

**Comment by redknitin** [comment]
Hi @kamilamin !

I've just updated the [CONTRIBUTING](https://github.com/redknitin/Helpdesk/blob/master/CONTRIBUTING.md) file with instructions on setting up a development environment.

I'll close this pull request for now.

**Pull request closed without merging**
